const paragraphs=[
    "Sport pertains to any form of physical activity or game, often competitive and organized, that aims to use, maintain, or improve physical ability and skills while providing enjoyment to participants and, in some cases, entertainment to spectators. Sports can, through casual or organized participation, improve participants' physical health. Hundreds of sports exist, from those between single contestants, through to those with hundreds of simultaneous participants, either in teams or competing as individuals. In certain sports such as racing, many contestants may compete, simultaneously or consecutively, with one winner; in others, the contest  is between two sides, each attempting to exceed the other. Some sports allow a tie or draw, in which there is no single winner; others provide tie-breaking methods to ensure one winner. A number of contests may be arranged in a tournament producing a champion. Many sports leagues make an annual champion by arranging games in a regular sports season, followed in some cases by playoffs.",

   "Entertainment is a form of activity that holds the attention and interest of an audience or gives pleasure and delight. It can be an idea or a task, but it is more likely to be one of the activities or events that have developed over thousands of years specifically for the purpose of keeping an audience's attention. Although people's attention is held by different things because individuals have different preferences, most forms of entertainment are recognisable and familiar. Storytelling, music, drama, dance, and different kinds of performance exist in all cultures, were supported in royal courts, and developed into sophisticated forms over time, becoming available to all citizens. The process has been accelerated in modern times by an entertainment industry that records and sells entertainment products. Entertainment evolves and can be adapted to suit any scale, ranging from an individual who chooses private entertainment from a now enormous array of pre-recorded products, to a banquet adapted for two, to any size or type of party with appropriate music and dance, to performances intended for thousands, and even for a global audience." ,

   "The history of science spans the majority of the historical record, with the earliest written records of identifiable predecessors to modern science dating to Bronze Age Egypt and Mesopotamia from around 3000 to 1200 BCE. Their contributions to mathematics, astronomy, and medicine entered and shaped the Greek natural philosophy of classical antiquity, whereby formal attempts were made to provide explanations of events in the physical world based on natural causes, while further advancements, including the introduction of the Hindu Arabic numeral system, were made during the Golden Age of India. Scientific research deteriorated in these regions after the fall of the Western Roman Empire during the early middle ages , but in the Medieval renaissances scholarship flourished again. Some Greek manuscripts lost in Western Europe were preserved and expanded upon in the Middle East during the Islamic Golden Age and later by the efforts of Byzantine Greek scholars who brought Greek manuscripts from the dying Byzantine Empire to Western Europe in the Renaissance.",

   "The deep sea, a realm shrouded in darkness, holds mysteries that continue to captivate the imagination of scientists and explorers alike. In the abyssal depths, where sunlight can no longer penetrate, unique and bizarre creatures have adapted to survive under extreme pressure and low temperatures. From the elusive giant squid, with its enormous tentacles, to bioluminescent jellyfish that light up the inky blackness, the deep sea is a treasure trove of biological diversity. Scientists deploy cutting-edge technology, such as remotely operated vehicles and autonomous underwater vehicles, to explore these uncharted waters. As researchers delve deeper into the ocean's secrets, they uncover hydrothermal vents spewing mineral-rich fluids, supporting ecosystems that defy expectations. The deep sea remains a frontier of exploration, promising to reveal more about the Earth's history, the potential for undiscovered species, and the interconnectedness of life in the most remote parts of our planet. The quest to understand and protect this mysterious realm continues to push the boundaries of scientific knowledge.",

   "Cultural diversity is a tapestry woven with threads of unique traditions, languages, and customs that enrich the global human experience. Every corner of the world boasts its own vibrant mosaic of beliefs and practices, contributing to the kaleidoscope of humanity. From the lively festivals that celebrate ancient rituals to the rich tapestries of art and cuisine, each culture adds a distinctive hue to the global canvas. Embracing diversity not only fosters a deeper understanding between communities but also allows for the exchange of ideas that can shape the course of history. In a world interconnected by technology, the celebration of cultural differences becomes a bridge that connects people across borders. As societies learn from one another, the collective wisdom gained from this rich diversity becomes a powerful force for positive change, promoting tolerance, empathy, and a shared vision of a harmonious world where all cultures are valued and respected.",

   "The world is undergoing a transformative shift towards renewable energy sources as societies recognize the urgent need to address climate change. Wind turbines gracefully spin against the horizon, harnessing the power of the wind, while solar panels glisten in the sunlight, converting it into clean electricity. This global push towards sustainability signifies a departure from fossil fuels and a commitment to a greener future. Governments, businesses, and individuals are investing in innovative technologies, such as advanced battery storage and tidal energy, to further reduce carbon footprints and pave the way for a more environmentally conscious and sustainable world. As the renewable energy sector continues to grow, it not only mitigates the impact of climate change but also fosters economic growth and job creation in emerging green industries.",

   "In the digital age, technology has become an integral part of our daily lives, reshaping how we communicate, work, and interact. From the convenience of smartphones to the power of artificial intelligence, technological advancements have revolutionized various aspects of modern society. While these innovations bring unprecedented efficiency and connectivity, they also raise ethical questions about privacy, job displacement, and the impact on mental well-being. Striking a balance between harnessing the benefits of technology and addressing its challenges is crucial as we navigate the ever-evolving landscape of the digital era. The transformative potential of technology is evident in fields such as healthcare, education, and transportation, offering opportunities for positive change on a global scale.",

   "In a world inundated with screens and instant gratification, the joy of reading remains a timeless pleasure. The act of flipping through the pages of a book, immersing oneself in a captivating story, or exploring the depths of knowledge within the written word is a unique and fulfilling experience. Books serve as windows to different worlds, offering insights, escapism, and the chance to broaden one's perspective. Whether it's fiction that transports the imagination or non-fiction that informs and educates, the written word continues to be a source of inspiration and intellectual nourishment in an increasingly fast-paced and digitalized society. The revival of book clubs, literary festivals, and online reading communities underscores the enduring appeal of reading as a communal and enriching activity, fostering connections among individuals who share a passion for the written word.",

   "Social media has undergone a profound evolution, transforming from a simple means of communication to a powerful force shaping societal dynamics. Platforms like Facebook, Twitter, and Instagram have redefined how we connect, share information, and engage with the world around us. The impact of social media extends beyond personal connections, influencing public discourse, activism, and even political landscapes. While it facilitates global communication and the dissemination of information, it also raises concerns about privacy, misinformation, and the potential for social division. The evolving nature of social media prompts ongoing discussions about its ethical use, regulation, and the responsibility of tech companies in ensuring a positive and inclusive online environment.",

   "Space exploration stands as a testament to humanity's insatiable curiosity and the relentless pursuit of knowledge. The vast expanse of the cosmos, dotted with celestial bodies and mysteries, has fueled our collective desire to explore the unknown. From the historic Apollo moon missions to contemporary endeavors like the Mars rovers and deep-space telescopes, space agencies and private enterprises alike contribute to expanding our understanding of the universe. Beyond the scientific discoveries, space exploration inspires innovation, pushing the boundaries of technology and engineering. As we reach toward the stars, the quest for knowledge extends not only to the origins of the cosmos but also to the potential for life beyond Earth, sparking philosophical contemplations about our place in the cosmos and the possibility of interstellar exploration in the future.",

   "Biodiversity, the variety of life on Earth, is crucial for the health and resilience of ecosystems. From lush rainforests to coral reefs, diverse habitats harbor a multitude of species, each playing a unique role in maintaining ecological balance. However, human activities, such as deforestation, pollution, and climate change, pose significant threats to biodiversity. Conservation efforts aim to protect endangered species, preserve habitats, and promote sustainable practices to mitigate these impacts. The loss of biodiversity not only diminishes the intrinsic value of nature but also poses risks to human well-being, affecting food security, medicine, and the overall stability of ecosystems. Recognizing the interconnectedness of all living things underscores the importance of global collaboration in safeguarding biodiversity for future generations."


]